# Dockerfile

# Etapa 1: Construcción de dependencias
ARG VARIANT=3.14
# ARG BUILDPLATFORM=linux/amd64
# FROM --platform=${BUILDPLATFORM} python:${VARIANT}-slim
FROM python:${VARIANT}-slim


# Instalar dependencias básicas del sistema
RUN apt-get update && apt-get install -y \
    curl build-essential zip && \
    rm -rf /var/lib/apt/lists/*

# Crea directorio de trabajo
WORKDIR /app

# Copia los requisitos
COPY requirements.txt .

# Instala dependencias con compatibilidad para Lambda (manylinux2014)
RUN pip install --upgrade pip && pip install --no-cache-dir -r requirements.txt

# Copia el resto de la app
COPY . .

EXPOSE 3003

CMD ["python", "main.py"]
