/*
 * Photo gallery for the Cumbre Nacional Minera landing.
 *
 * Renders one titled section per event day from window.GALLERY_DAYS
 * (see js/galeria-manifest.js). Each day shows a responsive grid of thumbnail
 * cards; a single lightbox spans every day so the user can navigate across the
 * whole set with the arrows/keyboard and download the original full-resolution
 * file.
 *
 * Manifest shape (generated by tools/build_gallery.sh):
 *   window.GALLERY_DAYS = [{ title, dir, photos: [name, ...] }, ...]
 *
 * Asset tiers per photo:
 *   assets/galeria/thumbs/<name>     -> grid card
 *   assets/galeria/web/<name>        -> lightbox viewer
 *   assets/galeria/<dir>/<name>      -> download (original, full quality)
 */
(function () {
  'use strict';

  var BASE = 'assets/galeria/';
  var days = window.GALLERY_DAYS || [];

  var container = document.getElementById('galleryGrid');
  var empty = document.getElementById('galleryEmpty');
  if (!container) {
    return;
  }

  // Flat list backing the lightbox: keeps navigation continuous across days.
  var items = [];
  days.forEach(function (day) {
    (day.photos || []).forEach(function (name) {
      items.push({ name: name, dir: day.dir, title: day.title });
    });
  });

  // Nothing uploaded yet: keep the "Próximamente" empty state visible.
  if (!items.length) {
    if (empty) {
      empty.hidden = false;
    }
    return;
  }
  if (empty) {
    empty.hidden = true;
  }

  function labelFor(index) {
    var item = items[index];
    return 'Cumbre Nacional Minera 2026 - ' + item.title + ' - foto ' + (index + 1);
  }

  // --- Build one titled grid per day ---------------------------------------
  var fragment = document.createDocumentFragment();
  var globalIndex = 0;
  days.forEach(function (day) {
    var photos = day.photos || [];
    if (!photos.length) {
      return;
    }

    var heading = document.createElement('h3');
    heading.className = 'gallery-day';
    heading.innerHTML = '<i class="fa-regular fa-calendar-days"></i> ' + day.title;
    fragment.appendChild(heading);

    var grid = document.createElement('div');
    grid.className = 'gallery-grid';

    photos.forEach(function (name) {
      var index = globalIndex++;
      var card = document.createElement('button');
      card.type = 'button';
      card.className = 'gallery-item';
      card.setAttribute('aria-label', 'Ampliar ' + labelFor(index));
      card.dataset.index = String(index);

      var img = document.createElement('img');
      img.src = BASE + 'thumbs/' + name;
      img.alt = labelFor(index);
      img.loading = 'lazy';
      img.decoding = 'async';

      var badge = document.createElement('span');
      badge.className = 'gallery-zoom';
      badge.innerHTML = '<i class="fa-solid fa-magnifying-glass-plus"></i>';

      card.appendChild(img);
      card.appendChild(badge);
      grid.appendChild(card);
    });

    fragment.appendChild(grid);
  });
  container.appendChild(fragment);

  // --- Lightbox -------------------------------------------------------------
  var lightbox = document.getElementById('lightbox');
  var lbImage = document.getElementById('lightboxImage');
  var lbCounter = document.getElementById('lightboxCounter');
  var lbDownload = document.getElementById('lightboxDownload');
  var current = -1;

  function show(index) {
    if (index < 0) {
      index = items.length - 1;
    } else if (index >= items.length) {
      index = 0;
    }
    current = index;
    var item = items[index];
    lbImage.src = BASE + 'web/' + item.name;
    lbImage.alt = labelFor(index);
    lbDownload.href = BASE + item.dir + '/' + item.name;
    lbDownload.setAttribute('download', item.name);
    lbCounter.textContent = item.title + ' · ' + (index + 1) + ' / ' + items.length;
  }

  function open(index) {
    show(index);
    lightbox.classList.add('is-open');
    lightbox.setAttribute('aria-hidden', 'false');
    document.body.classList.add('no-scroll');
  }

  function close() {
    lightbox.classList.remove('is-open');
    lightbox.setAttribute('aria-hidden', 'true');
    document.body.classList.remove('no-scroll');
    lbImage.src = '';
    current = -1;
  }

  container.addEventListener('click', function (event) {
    var card = event.target.closest('.gallery-item');
    if (card) {
      open(parseInt(card.dataset.index, 10));
    }
  });

  lightbox.addEventListener('click', function (event) {
    var action = event.target.closest('[data-action]');
    if (!action) {
      // Click on the dark backdrop (not the image) closes the lightbox.
      if (event.target === lightbox || event.target.classList.contains('lightbox-stage')) {
        close();
      }
      return;
    }
    var kind = action.dataset.action;
    if (kind === 'close') {
      close();
    } else if (kind === 'prev') {
      show(current - 1);
    } else if (kind === 'next') {
      show(current + 1);
    }
    // 'download' is a native anchor; let the browser handle it.
  });

  document.addEventListener('keydown', function (event) {
    if (current === -1) {
      return;
    }
    if (event.key === 'Escape') {
      close();
    } else if (event.key === 'ArrowLeft') {
      show(current - 1);
    } else if (event.key === 'ArrowRight') {
      show(current + 1);
    }
  });
})();
