# Usamos Python 3.13 para estabilidad en producción
FROM python:3.14-slim

WORKDIR /app

# Dependencias del sistema para MySQL y herramientas de compilación
RUN apt-get update && apt-get install -y \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# Exponemos el puerto definido en tus variables de entorno (3020)
EXPOSE 3020

CMD ["python", "main.py"]
