'''
    Products Schemas (Request/Response)
'''
from typing import List, Optional
from datetime import datetime
from fastapi import Query
from pydantic import BaseModel, Field, ConfigDict

# --- BASE SCHEMAS ---
class ProductBaseSchemaConfig(BaseModel):
    '''
        Base schema with `from_attributes=True` enabled to handle
        ORM objects from SQLAlchemy.
    '''
    model_config = ConfigDict(from_attributes = True)

# --- PRODUCT SCHEMAS ---

class ProductBaseSchema(ProductBaseSchemaConfig):
    '''
        Base schema for product data fields.
    '''
    name: str = Field(
        ...,
        max_length = 255,
        description = 'Name of the product in the catalog.'
    )
    description: Optional[str] = Field(
        None,
        max_length = 500,
        description = 'Detailed description of the product.'
    )
    category_1_code: str = Field(
        ...,
        max_length = 10,
        description = 'First category code (XXX segment, mandatory).'
    )
    category_2_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Second category code (YYY segment, optional).'
    )
    category_3_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Third category code (ZZZ segment, optional).'
    )
    category_4_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Fourth category code (WWW segment, optional).'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Current status of the product (e.g., ACTIVE, INACTIVE).'
    )

class ProductCreateSchema(ProductBaseSchema):
    '''
        Schema for creating a new product.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning the product catalog.'
    )

class ProductUpdateSchema(ProductBaseSchema):
    '''
        Schema for updating an existing product. All fields are optional.
    '''
    name: Optional[str] = None
    description: Optional[str] = None
    category_1_code: Optional[str] = None
    category_2_code: Optional[str] = None
    category_3_code: Optional[str] = None
    category_4_code: Optional[str] = None
    status: Optional[str] = None

class ProductResponseSchema(ProductBaseSchema):
    '''
        Response schema for a product, including generated fields and timestamps.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the product record.'
    )
    sku: str = Field(
        ...,
        description = 'Stock Keeping Unit (XXX.YYY.ZZZ.WWW.SEC) generated by the system.'
    )
    created_at: Optional[datetime] = Field(
        None,
        description = 'Timestamp when the record was created.'
    )

class ProductListResponseSchema(ProductBaseSchemaConfig):
    '''
        Response schema for a paginated list of products.
    '''
    items: List[ProductResponseSchema]
    total: int

class ProductFilterSchema(BaseModel):
    '''
        Schema to encapsulate filtering parameters for Products.
    '''
    company_id: int = Query(..., description = 'Company ID (Mandatory for filtering).')
    name: Optional[str] = Query(None, description = 'Filter by product name (partial match).')
    sku: Optional[str] = Query(None, description = 'Filter by exact SKU.')
    status: Optional[str] = Query(None, description = 'Filter by status (e.g., ACTIVE).')

    class Config:# pylint: disable=too-few-public-methods
        '''
            'Pydantic config.'
        '''
        arbitrary_types_allowed = True

# --- SKU EQUIVALENCY SCHEMAS ---

class SKUEquivalencyBaseSchema(ProductBaseSchema):
    '''
        Base schema for SKU Equivalency fields.
        Uses product_sku for API input, following the POS Inventory pattern.
    '''
    product_sku: str = Field(
        ...,
        description = 'Internal SKU code (XXX.YYY.ZZZ.WWW.SEC) to map.'
    )
    external_system_name: str = Field(
        ...,
        max_length = 100,
        description = 'Name of the external system (e.g., "SAP", "CLIENT_ERP").'
    )
    external_product_code: str = Field(
        ...,
        max_length = 50,
        description = 'Code of the product in the external system.'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Status of the equivalency (e.g., ACTIVE, INACTIVE).'
    )

class SKUEquivalencyCreateSchema(SKUEquivalencyBaseSchema):
    '''
        Schema for creating a new SKU Equivalency.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning this mapping.'
    )

class SKUEquivalencyUpdateSchema(ProductBaseSchema):
    '''
        Schema for updating an SKU Equivalency. All fields are optional.
    '''
    product_sku: Optional[str] = None
    external_system_name: Optional[str] = None
    external_product_code: Optional[str] = None
    status: Optional[str] = None

class SKUEquivalencyResponseSchema(SKUEquivalencyBaseSchema):
    '''
        Response schema for an SKU Equivalency.
    '''
    id: int
    company_id: int
    product_id: int
    created_at: Optional[datetime]

# --- PRODUCT ASSIGNMENT POS SCHEMAS ---

class ProductAssignmentPOSBaseSchema(ProductBaseSchemaConfig):
    '''
        Base schema for Product to POS Assignment fields.
    '''
    product_sku: str = Field(
        ...,
        description = 'Internal SKU code (XXX.YYY.ZZZ.WWW.SEC) to assign.'
    )
    point_of_sale_id: int = Field(
        ...,
        description = 'ID of the Point of Sale to assign the product to.'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Status of the assignment (e.g., ACTIVE, INACTIVE).'
    )

class ProductAssignmentPOSCreateSchema(ProductAssignmentPOSBaseSchema):
    '''
        Schema for creating a new Product to POS Assignment.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning this assignment.'
    )

class ProductAssignmentPOSUpdateSchema(ProductBaseSchemaConfig):
    '''
        Schema for updating a Product to POS Assignment.
    '''
    # Only status is updatable. To change product/pos, delete and recreate.
    status: Optional[str] = Field(
        None,
        max_length = 20,
        description = 'New status for the assignment.'
    )

class ProductAssignmentPOSResponseSchema(ProductBaseSchemaConfig):
    '''
        Response schema for a Product to POS Assignment.
    '''
    id: int
    company_id: int
    product_id: int # Returns the internal ID
    point_of_sale_id: int
    status: str
    created_at: Optional[datetime]
class ProductAssignmentPOSFilterSchema(BaseModel):
    '''
        Schema to encapsulate filtering parameters for Product POS Assignments.
    '''
    company_id: int = Query(..., description = 'Company ID (Mandatory for filtering).')
    product_id: Optional[int] = Query(None, description = 'Filter by internal Product ID.')
    point_of_sale_id: Optional[int] = Query(None, description = 'Filter by Point of Sale ID.')
    status: Optional[str] = Query(None, description = 'Filter by status (e.g., ACTIVE).')

    class Config:# pylint: disable=too-few-public-methods
        '''
            Pydantic config.
        '''
        arbitrary_types_allowed = True

class ProductAssignmentPOSListResponseSchema(ProductBaseSchemaConfig):
    '''
        Response schema for a paginated list of Product POS Assignments.
    '''
    items: List[ProductAssignmentPOSResponseSchema]
    total: int
