'''
    Trade Schemas (Request/Response) for Products and Points of Sale
'''
from typing import List, Optional
from datetime import datetime
from fastapi import Query
from pydantic import BaseModel, Field, ConfigDict

# --- BASE SCHEMAS ---
class TradeBaseSchema(BaseModel):
    '''
        Base schema with `from_attributes=True` enabled to handle
        ORM objects from SQLAlchemy.
    '''
    model_config = ConfigDict(from_attributes = True)

# --- PRODUCT SCHEMAS ---

class ProductBaseSchema(TradeBaseSchema):
    '''
        Base schema for product data fields.
    '''
    name: str = Field(
        ...,
        max_length = 255,
        description = 'Name of the product in the catalog.'
    )
    description: Optional[str] = Field(
        None,
        max_length = 500,
        description = 'Detailed description of the product.'
    )
    category_1_code: str = Field(
        ...,
        max_length = 10,
        description = 'First category code (XXX segment, mandatory).'
    )
    category_2_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Second category code (YYY segment, optional).'
    )
    category_3_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Third category code (ZZZ segment, optional).'
    )
    category_4_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Fourth category code (WWW segment, optional).'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Current status of the product (e.g., ACTIVE, INACTIVE).'
    )

class ProductCreateSchema(ProductBaseSchema):
    '''
        Schema for creating a new product.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning the product catalog.'
    )

class ProductUpdateSchema(ProductBaseSchema):
    '''
        Schema for updating an existing product. All fields are optional.
    '''
    name: Optional[str] = None
    description: Optional[str] = None
    category_1_code: Optional[str] = None
    category_2_code: Optional[str] = None
    category_3_code: Optional[str] = None
    category_4_code: Optional[str] = None
    status: Optional[str] = None

class ProductResponseSchema(ProductBaseSchema):
    '''
        Response schema for a product, including generated fields and timestamps.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the product record.'
    )
    sku: str = Field(
        ...,
        description = 'Stock Keeping Unit (XXX.YYY.ZZZ.WWW.SEC) generated by the system.'
    )
    created_at: Optional[datetime] = Field(
        None,
        description = 'Timestamp when the record was created.'
    )
    updated_at: Optional[datetime] = Field(
        None,
        description = 'Timestamp when the record was last updated.'
    )

class ProductListResponseSchema(TradeBaseSchema):
    '''
        Response schema for a paginated list of products.
    '''
    items: List[ProductResponseSchema]
    total: int

class ProductFilterSchema(BaseModel):
    '''
        Schema to encapsulate filtering parameters for Products.
    '''
    company_id: int = Query(..., description = 'Company ID (Mandatory for filtering).')
    name: Optional[str] = Query(None, description = 'Filter by product name (partial match).')
    sku: Optional[str] = Query(None, description = 'Filter by exact SKU.')
    status: Optional[str] = Query(None, description = 'Filter by status (e.g., ACTIVE).')

    class Config:# pylint: disable=too-few-public-methods
        '''
            'Pydantic config.'
        '''
        arbitrary_types_allowed = True

# --- POINT OF SALE (POS) INVENTORY SCHEMAS ---

class POSInventoryBaseSchema(TradeBaseSchema):
    '''
        Base schema for detailed Point of Sale Inventory fields.
    '''
    product_sku: str = Field(
        ...,
        description = 'SKU of the product being tracked.'
    )
    location: str = Field(
        ...,
        max_length = 50,
        description = 'Location within the POS (e.g., Sala or Almacén).'
    )
    batch_number: str = Field(
        ...,
        max_length = 50,
        description = 'Batch or lot number of the product units.'
    )
    expiration_date: str = Field(
        ...,
        description = 'Expiration date of the product units (YYYY-MM-DD).'
    )
    is_short_date: Optional[bool] = Field(
        False,
        description = 'Flag indicating if the product is on short date (True/Red, False/Green).'
    )
    quantity: int = Field(
        ...,
        ge = 0,
        description = 'Total quantity of units for this specific batch/location/SKU.'
    )

class POSInventoryCreateSchema(POSInventoryBaseSchema):
    '''
        Schema for creating a new POS Inventory detail.
    '''

class POSInventoryUpdateSchema(POSInventoryBaseSchema):
    '''
        Schema for updating a POS Inventory detail.
    '''
    product_sku: Optional[str] = None
    location: Optional[str] = None
    batch_number: Optional[str] = None
    expiration_date: Optional[str] = None
    quantity: Optional[int] = None

class POSInventoryResponseSchema(TradeBaseSchema):
    '''
        Response schema for a POS Inventory detail, including ID and timestamps.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the inventory record.'
    )
    point_of_sale_id: int = Field(
        ...,
        description = 'ID of the parent Point of Sale.'
    )
    product_id: int = Field(
        ...,
        description = 'ID of the product being tracked.'
    )
    location: str = Field(
        ...,
        max_length = 50,
        description = 'Location within the POS (e.g., Sala or Almacén).'
    )
    batch_number: str = Field(
        ...,
        max_length = 50,
        description = 'Batch or lot number of the product units.'
    )
    expiration_date: datetime = Field(
        ...,
        description = 'Expiration date of the product units.'
    )
    is_short_date: Optional[bool] = Field(
        False,
        description = 'Flag indicating if the product is on short date (True/Red, False/Green).'
    )
    quantity: int = Field(
        ...,
        ge = 0,
        description = 'Total quantity of units for this specific batch/location/SKU.'
    )
    created_at: Optional[datetime] = Field(
        None,
        description = 'Timestamp when the record was created.'
    )
    updated_at: Optional[datetime] = Field(
        None,
        description = 'Timestamp when the record was last updated.'
    )

# --- POINT OF SALE (POS) SCHEMAS ---

class PointOfSaleBaseSchema(TradeBaseSchema):
    '''
        Base schema for Point of Sale (PDV) data.
    '''
    name: str = Field(
        ...,
        max_length = 255,
        description = 'Commercial name of the Point of Sale.'
    )
    external_code: Optional[str] = Field(
        None,
        max_length = 50,
        description = 'External code used by the client for this POS.'
    )
    address: Optional[str] = Field(
        None,
        max_length = 255,
        description = 'Physical address of the POS.'
    )
    is_active: Optional[bool] = Field(
        True,
        description = 'Status of the POS.'
    )
    latitude: float = Field(
        ...,
        description = 'Geographical latitude of the POS.'
    )
    longitude: float = Field(
        ...,
        description = 'Geographical longitude of the POS.'
    )

class PointOfSaleCreateSchema(PointOfSaleBaseSchema):
    '''
        Schema for creating a new Point of Sale.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company that owns the POS record.'
    )
    initial_inventory: Optional[List[POSInventoryBaseSchema]] = Field(
        None,
        description = 'Initial inventory details to be associated with this POS.'
    )

class PointOfSaleUpdateSchema(PointOfSaleBaseSchema):
    '''
        Schema for updating an existing Point of Sale. All fields are optional.
    '''
    # Override fields from base to make them optional for updates
    name: Optional[str] = None
    is_active: Optional[bool] = None
    address: Optional[str] = None
    external_code: Optional[str] = None

class PointOfSaleResponseSchema(PointOfSaleBaseSchema):
    '''
        Response schema for a Point of Sale, including ID, timestamps, and inventory.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the POS record.'
    )
    company_id: int = Field(
        ...,
        description = 'ID of the company that owns the POS record.'
    )
    inventory: List[POSInventoryResponseSchema] = Field(
        [],
        description = 'Detailed local inventory associated with this Point of Sale.'
    )
    created_at: Optional[datetime] = Field(
        None,
        description = 'Timestamp when the record was created.'
    )

class POSListResponseSchema(TradeBaseSchema):
    '''
        Response schema for a paginated list of Points of Sale.
    '''
    items: List[PointOfSaleResponseSchema]
    total: int

class POSFilterSchema(BaseModel):
    '''
        Schema to encapsulate filtering parameters for Points of Sale.
    '''
    company_id: int = Query(..., description = 'Company ID (Mandatory for filtering).')
    name: Optional[str] = Query(None, description = 'Filter by POS name (partial match).')
    external_code: Optional[str] = Query(None, description = 'Filter by exact external code.')
    is_active: Optional[bool] = Query(None, description = 'Filter by status (True/False).')

    class Config:# pylint: disable=too-few-public-methods
        '''
            'Pydantic config.'
        '''
        arbitrary_types_allowed = True

# --- SKU EQUIVALENCY SCHEMAS ---

class SKUEquivalencyBaseSchema(TradeBaseSchema):
    '''
        Base schema for SKU Equivalency fields.
        Uses product_sku for API input, following the POS Inventory pattern.
    '''
    product_sku: str = Field(
        ...,
        description = 'Internal SKU code (XXX.YYY.ZZZ.WWW.SEC) to map.'
    )
    external_system_name: str = Field(
        ...,
        max_length = 100,
        description = 'Name of the external system (e.g., "SAP", "CLIENT_ERP").'
    )
    external_product_code: str = Field(
        ...,
        max_length = 50,
        description = 'Code of the product in the external system.'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Status of the equivalency (e.g., ACTIVE, INACTIVE).'
    )

class SKUEquivalencyCreateSchema(SKUEquivalencyBaseSchema):
    '''
        Schema for creating a new SKU Equivalency.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning this mapping.'
    )

class SKUEquivalencyUpdateSchema(TradeBaseSchema):
    '''
        Schema for updating an SKU Equivalency. All fields are optional.
    '''
    product_sku: Optional[str] = None
    external_system_name: Optional[str] = None
    external_product_code: Optional[str] = None
    status: Optional[str] = None

class SKUEquivalencyResponseSchema(SKUEquivalencyBaseSchema):
    '''
        Response schema for an SKU Equivalency.
    '''
    id: int
    company_id: int
    product_id: int
    created_at: Optional[datetime]

# --- PRODUCT ASSIGNMENT POS SCHEMAS ---

class ProductAssignmentPOSBaseSchema(TradeBaseSchema):
    '''
        Base schema for Product to POS Assignment fields.
    '''
    product_sku: str = Field(
        ...,
        description = 'Internal SKU code (XXX.YYY.ZZZ.WWW.SEC) to assign.'
    )
    point_of_sale_id: int = Field(
        ...,
        description = 'ID of the Point of Sale to assign the product to.'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Status of the assignment (e.g., ACTIVE, INACTIVE).'
    )

class ProductAssignmentPOSCreateSchema(ProductAssignmentPOSBaseSchema):
    '''
        Schema for creating a new Product to POS Assignment.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning this assignment.'
    )

class ProductAssignmentPOSUpdateSchema(TradeBaseSchema):
    '''
        Schema for updating a Product to POS Assignment.
    '''
    # Only status is updatable. To change product/pos, delete and recreate.
    status: Optional[str] = Field(
        None,
        max_length = 20,
        description = 'New status for the assignment.'
    )

class ProductAssignmentPOSResponseSchema(ProductAssignmentPOSBaseSchema):
    '''
        Response schema for a Product to POS Assignment.
    '''
    id: int
    company_id: int
    product_id: int # Returns the internal ID
    created_at: Optional[datetime]
    # updated_at is omitted (handled by EVENTS)

class ProductAssignmentPOSFilterSchema(BaseModel):
    '''
        Schema to encapsulate filtering parameters for Product POS Assignments.
    '''
    company_id: int = Query(..., description = 'Company ID (Mandatory for filtering).')
    product_id: Optional[int] = Query(None, description = 'Filter by internal Product ID.')
    point_of_sale_id: Optional[int] = Query(None, description = 'Filter by Point of Sale ID.')
    status: Optional[str] = Query(None, description = 'Filter by status (e.g., ACTIVE).')

    class Config:# pylint: disable=too-few-public-methods
        '''
            Pydantic config.
        '''
        arbitrary_types_allowed = True

class ProductAssignmentPOSListResponseSchema(TradeBaseSchema):
    '''
        Response schema for a paginated list of Product POS Assignments.
    '''
    items: List[ProductAssignmentPOSResponseSchema]
    total: int

# --- A.3. TRADE PLANNING SCHEMAS ---

class TradePlanningBaseSchema(TradeBaseSchema):
    '''
        Base schema for Trade Planning fields.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company that owns this planning record.'
    )
    planning_id: int = Field(
        ...,
        description = 'ID from the PLANNING microservice.'
    )
    user_id: int = Field(
        ...,
        description = 'ID of the user assigned to this plan (from frontend).'
    )
    point_of_sale_id: int = Field(
        ...,
        description = 'ID of the Point of Sale (from t_points_of_sale).'
    )
    planned_workload_minutes: int = Field(
        ...,
        gt=0,
        description = 'Planned workload in minutes (Business Rule).'
    )
    status: Optional[str] = Field(
        'PENDING',
        max_length=20,
        description = 'Status of this planning entry (e.g., PENDING, COMPLETED).'
    )
    comments: Optional[str] = Field(
        None,
        description = 'Optional comments for this planning entry.'
    )


class TradePlanningCreateSchema(TradePlanningBaseSchema):# pylint: disable=too-few-public-methods
    '''
        Schema for creating a new Trade Planning entry.
    '''
    # pass


class TradePlanningUpdateSchema(TradeBaseSchema):
    '''
        Schema for updating an existing Trade Planning entry.
    '''
    # Only status and comments are updatable.
    # To change core data, delete and recreate.
    status: Optional[str] = Field(
        None,
        max_length=20,
        description = 'New status for the planning entry.'
    )
    comments: Optional[str] = Field(
        None,
        description = 'Optional comments for this planning entry.'
    )


class TradePlanningResponseSchema(TradePlanningBaseSchema):
    '''
        Response schema for a Trade Planning entry.
    '''
    id: int
    actual_workload_minutes: Optional[int]
    workload_difference_minutes: Optional[int]
    created_at: Optional[datetime]

    point_of_sale: Optional[PointOfSaleResponseSchema] = None


class TradePlanningFilterSchema(BaseModel):
    '''
        Schema to encapsulate filtering parameters for Trade Planning entries.
    '''
    company_id: int = Query(..., description = 'Company ID (Mandatory for filtering).')
    planning_id: Optional[int] = Query(None, description = 'Filter by PLANNING microservice ID.')
    user_id: Optional[int] = Query(None, description = 'Filter by User ID.')
    point_of_sale_id: Optional[int] = Query(None, description = 'Filter by Point of Sale ID.')
    status: Optional[str] = Query(None, description = 'Filter by status (e.g., PENDING).')

    class Config:# pylint: disable=too-few-public-methods
        '''
        Pydantic config.
        '''
        arbitrary_types_allowed = True


class TradePlanningListResponseSchema(TradeBaseSchema):
    '''
        Response schema for a paginated list of Trade Planning entries.
    '''
    items: List[TradePlanningResponseSchema]
    total: int


# --- Schema for Workload Calculation Endpoint (PATCH) ---

class TradePlanningWorkloadUpdateSchema(TradeBaseSchema):
    '''
        Schema for the PATCH endpoint to calculate and update workload.
        Frontend provides the check-in and check-out times.
    '''
    check_in_time: datetime = Field(
        ...,
        description = 'Actual check-in time from LOCALIZATION (t_attendances).'
    )
    check_out_time: datetime = Field(
        ...,
        description = 'Actual check-out time from LOCALIZATION (t_attendances).'
    )
