'''
    Trade Schemas (Request/Response) for Products and Points of Sale
'''
from typing import List, Optional
from datetime import datetime
from pydantic import BaseModel, Field, ConfigDict

# --- BASE SCHEMAS ---

class TradeBaseSchema(BaseModel):
    '''
        Base schema with `from_attributes=True` enabled to handle
        ORM objects from SQLAlchemy.
    '''
    model_config = ConfigDict(from_attributes = True)

# --- PRODUCT SCHEMAS ---

class ProductBaseSchema(TradeBaseSchema):
    '''
        Base schema for product data fields.
    '''
    name: str = Field(
        ...,
        max_length = 255,
        description = 'Name of the product in the catalog.'
    )
    description: Optional[str] = Field(
        None,
        max_length = 500,
        description = 'Detailed description of the product.'
    )
    category_1_code: str = Field(
        ...,
        max_length = 10,
        description = 'First category code (XXX segment, mandatory).'
    )
    category_2_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Second category code (YYY segment, optional).'
    )
    category_3_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Third category code (ZZZ segment, optional).'
    )
    category_4_code: Optional[str] = Field(
        '000',
        max_length = 10,
        description = 'Fourth category code (WWW segment, optional).'
    )
    status: Optional[str] = Field(
        'ACTIVE',
        max_length = 20,
        description = 'Current status of the product (e.g., ACTIVE, INACTIVE).'
    )


class ProductCreateSchema(ProductBaseSchema):
    '''
        Schema for creating a new product.
        The SKU will be generated by the service layer.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company owning the product catalog.'
    )


class ProductUpdateSchema(ProductBaseSchema):
    '''
        Schema for updating an existing product. All fields are optional.
    '''
    # Override fields from base to make them optional for updates
    name: Optional[str] = None
    category_1_code: Optional[str] = None


class ProductResponseSchema(ProductBaseSchema):
    '''
        Response schema for a product, including generated fields and timestamps.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the product record.'
    )
    sku: str = Field(
        ...,
        description = 'Stock Keeping Unit (XXX.YYY.ZZZ.WWW.SEC) generated by the system.'
    )
    created_at: datetime = Field(
        ...,
        description = 'Timestamp when the record was created.'
    )
    updated_at: datetime = Field(
        ...,
        description = 'Timestamp when the record was last updated.'
    )

# --- POINT OF SALE (POS) INVENTORY SCHEMAS ---

class POSInventoryBaseSchema(TradeBaseSchema):
    '''
        Base schema for detailed Point of Sale Inventory fields.
    '''
    product_id: int = Field(
        ...,
        description = 'ID of the product being tracked.'
    )
    location: str = Field(
        ...,
        max_length = 50,
        description = 'Location within the POS (e.g., Sala or Almacén).'
    )
    batch_number: str = Field(
        ...,
        max_length = 50,
        description = 'Batch or lot number of the product units.'
    )
    expiration_date: datetime = Field(
        ...,
        description = 'Expiration date of the product units.'
    )
    is_short_date: Optional[bool] = Field(
        False,
        description = 'Flag indicating if the product is on short date (True/Red, False/Green).'
    )
    quantity: int = Field(
        ...,
        ge = 0,
        description = 'Total quantity of units for this specific batch/location/SKU.'
    )


class POSInventoryCreateSchema(POSInventoryBaseSchema):
    '''
        Schema for creating a new POS Inventory detail.
    '''


class POSInventoryUpdateSchema(POSInventoryBaseSchema):
    '''
        Schema for updating a POS Inventory detail.
    '''
    product_id: Optional[int] = None
    location: Optional[str] = None
    batch_number: Optional[str] = None
    expiration_date: Optional[datetime] = None
    quantity: Optional[int] = None


class POSInventoryResponseSchema(POSInventoryBaseSchema):
    '''
        Response schema for a POS Inventory detail, including ID and timestamps.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the inventory record.'
    )
    point_of_sale_id: int = Field(
        ...,
        description = 'ID of the parent Point of Sale.'
    )
    created_at: datetime = Field(
        ...,
        description = 'Timestamp when the record was created.'
    )
    updated_at: datetime = Field(
        ...,
        description = 'Timestamp when the record was last updated.'
    )


# --- POINT OF SALE (POS) SCHEMAS ---

class PointOfSaleBaseSchema(TradeBaseSchema):
    '''
        Base schema for Point of Sale (PDV) data.
    '''
    name: str = Field(
        ...,
        max_length = 255,
        description = 'Commercial name of the Point of Sale.'
    )
    external_code: Optional[str] = Field(
        None,
        max_length = 50,
        description = 'External code used by the client for this POS.'
    )
    address: Optional[str] = Field(
        None,
        max_length = 255,
        description = 'Physical address of the POS.'
    )
    latitude: float = Field(
        ...,
        description = 'Geographical latitude of the POS.'
    )
    longitude: float = Field(
        ...,
        description = 'Geographical longitude of the POS.'
    )


class PointOfSaleCreateSchema(PointOfSaleBaseSchema):
    '''
        Schema for creating a new Point of Sale.
    '''
    company_id: int = Field(
        ...,
        description = 'ID of the company that owns the POS record.'
    )
    initial_inventory: Optional[List[POSInventoryCreateSchema]] = Field(
        None,
        description = 'Initial inventory details to be associated with this POS.'
    )


class PointOfSaleUpdateSchema(PointOfSaleBaseSchema):
    '''
        Schema for updating an existing Point of Sale. All fields are optional.
    '''
    # Override fields from base to make them optional for updates
    name: Optional[str] = None
    latitude: Optional[float] = None
    longitude: Optional[float] = None


class PointOfSaleResponseSchema(PointOfSaleBaseSchema):
    '''
        Response schema for a Point of Sale, including ID, timestamps, and inventory.
    '''
    id: int = Field(
        ...,
        description = 'Unique identifier for the POS record.'
    )
    company_id: int = Field(
        ...,
        description = 'ID of the company that owns the POS record.'
    )
    inventory: List[POSInventoryResponseSchema] = Field(
        [],
        description = 'Detailed local inventory associated with this Point of Sale.'
    )
    created_at: datetime = Field(
        ...,
        description = 'Timestamp when the record was created.'
    )
    updated_at: datetime = Field(
        ...,
        description = 'Timestamp when the record was last updated.'
    )
