'''
    Bolivian electronic invoicing: the SIAT algorithms.

    Everything in this file is deterministic and talks to nobody: the CUF is
    generated by OUR system, not by the tax office, so it can be implemented
    and tested whole before the authorization exists. What does depend on the
    SIN —the SOAP services, the CUIS, the CUFD and the control code— lives
    outside this module and is not written yet.

    Every function is verified against the worked example the SIAT itself
    publishes in `docs/siat/SIAT.md`; that example is the test.

    References, all in `docs/siat/SIAT.md`:
        - CUF generation
        - Modulus 11 algorithm
        - Base 16 algorithm
        - GZIP compression
'''
import base64
import gzip

from schemas.billing import CufInput

# Width of each CUF field, in the order they are concatenated. They add up to
# 53; the self-check digit takes it to 54.
CUF_WIDTHS = (
    ('nit', 13),
    ('issued_at', 17),
    ('branch', 4),
    ('modality', 1),
    ('emission_type', 1),
    ('invoice_type', 1),
    ('sector_document', 2),
    ('invoice_number', 10),
    ('point_of_sale', 4)
)


def check_digit(
    chain: str,
    limit: int = 9
) -> str:
    '''
        The self-check digit of a chain, by modulus 11.

        The SIAT publishes it in Java and in C#; this is that same sum. Each
        digit is multiplied by a factor that climbs from 2 to the limit and
        starts again, and the remainder decides: 10 writes "1", 11 writes "0".

        Args:
            chain (str): Chain of digits to verify.
            limit (int): Highest multiplier before restarting at 2.

        Returns:
            str: One digit.

        Raises:
            ValueError: The chain carries something that is not a digit.
    '''
    if not chain.isdigit():
        raise ValueError('Modulus 11 only accepts digits.')

    total, multiplier = 0, 2
    for char in reversed(chain):
        total += multiplier * int(char)
        multiplier += 1
        if multiplier > limit:
            multiplier = 2

    digit = ((total * 10) % 11) % 10
    if digit == 10:
        return '1'
    if digit == 11:
        return '0'
    return str(digit)


def cuf_chain(data: CufInput) -> str:
    '''
        The 53 digits that identify the invoice, before the check digit.

        Args:
            data (CufInput): Invoice data.

        Returns:
            str: A 53-digit chain, each field left-padded with zeros to its
                own width.
    '''
    values = {
        'nit': data.nit,
        'issued_at': data.issued_at.strftime('%Y%m%d%H%M%S') +
                     f'{data.issued_at.microsecond // 1000:03d}',
        'branch': str(data.branch),
        'modality': str(data.modality),
        'emission_type': str(data.emission_type),
        'invoice_type': str(data.invoice_type),
        'sector_document': str(data.sector_document),
        'invoice_number': str(data.invoice_number),
        'point_of_sale': str(data.point_of_sale)
    }
    return ''.join(values[field].zfill(width) for field, width in CUF_WIDTHS)


def build_cuf(
    data: CufInput,
    control_code: str | None = None
) -> str:
    '''
        The Unique Invoice Code (CUF).

        The 53-digit chain gets its check digit, the resulting number is
        written in base 16, and the control code returned by the CUFD service
        is concatenated at the end.

        Args:
            data (CufInput): Invoice data.
            control_code (str | None): Control code of the day's CUFD. Without
                it the CUF is incomplete and serves only for testing.

        Returns:
            str: The CUF.
    '''
    chain = cuf_chain(data)
    numeric = chain + check_digit(chain)
    # Base 16 of the whole number, not of each digit: the worked example in
    # the norm turns 54 decimal digits into 41 hexadecimal characters.
    base16 = format(int(numeric), 'X')
    return f'{base16}{control_code}' if control_code else base16


def pack(xml: str) -> str:
    '''
        The XML as the SOAP envelope expects it: compressed and base64.

        Args:
            xml (str): XML document of the invoice.

        Returns:
            str: The same document, gzip + base64.
    '''
    return base64.b64encode(gzip.compress(xml.encode('utf-8'))).decode('ascii')


def unpack(payload: str) -> str:
    '''
        The inverse of `pack`, to read back what was sent.

        Args:
            payload (str): A gzip + base64 chain.

        Returns:
            str: The original XML.
    '''
    return gzip.decompress(base64.b64decode(payload)).decode('utf-8')


def mask_card(number: str) -> str:
    '''
        A card number with its middle zeroed out.

        Phase II of the authorization requires it: the first four and the last
        four digits are kept and everything between them becomes zeros.

        Args:
            number (str): Number exactly as the buyer gave it.

        Returns:
            str: The masked number.

        Raises:
            ValueError: The number has fewer than eight digits.
    '''
    digits = ''.join(char for char in number if char.isdigit())
    if len(digits) < 8:
        raise ValueError('A card number cannot have fewer than 8 digits.')
    return f'{digits[:4]}{"0" * (len(digits) - 8)}{digits[-4:]}'
