# Dockerfile optimizado para Python 3.14
ARG VARIANT=3.14
FROM python:${VARIANT}-slim

# Instalar dependencias básicas del sistema
RUN apt-get update && apt-get install -y \
    curl build-essential zip && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copia los requisitos
COPY requirements.txt .

# 💡 MEJORA: Instalación para arquitectura ARM64 (Graviton)
# Cambiamos x86_64 por aarch64 para mayor rendimiento y menor costo en Lambda
RUN pip install --platform manylinux2014_aarch64 \
    --implementation cp \
    --python-version 3.14 \
    --only-binary=:all: \
    --target python/ \
    -r requirements.txt

# Copia el resto de la app
COPY . .

# Preparar la estructura para el ZIP de Lambda
RUN cp -r main.py controllers routes schemas services python/

# Crear el ZIP final
WORKDIR /app/python
RUN zip -r9 /app/lambda_function.zip .
