#!/usr/bin/env bash
#
# build_gallery.sh — Generates gallery derivatives and the grouped manifest.
#
# Originals are organized by day in subfolders named dia_<NN> (e.g. dia_23,
# dia_24). For every full-resolution photo in assets/galeria/dia_*/ this
# produces:
#   - assets/galeria/thumbs/<name>  ~600px longest side (grid cards)
#   - assets/galeria/web/<name>     ~1920px longest side (lightbox viewer)
# Derivatives stay flat (filenames are unique across days); the originals in
# their day folder are used as the download target.
#
# It then writes js/galeria-manifest.js with one ordered group per day. The
# day title is derived from the folder name: dia_23 -> "23 de julio".
# Re-run after adding or removing photos, then redeploy.
#
# Requires: sips (bundled with macOS).

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SRC="${ROOT}/assets/galeria"
THUMBS="${SRC}/thumbs"
WEB="${SRC}/web"
MANIFEST="${ROOT}/js/galeria-manifest.js"

THUMB_MAX=600
WEB_MAX=1920
THUMB_QUALITY=70
WEB_QUALITY=82

mkdir -p "${THUMBS}" "${WEB}"

# Day folders in chronological order (dia_23, dia_24, ...).
shopt -s nullglob
day_dirs=("${SRC}"/dia_*/)
shopt -u nullglob
IFS=$'\n' day_dirs=($(sort <<<"${day_dirs[*]}")); unset IFS

# Start the manifest.
{
    echo "// Auto-generated by tools/build_gallery.sh — do not edit by hand."
    echo "// Regenerate after adding or removing photos in assets/galeria/dia_*/."
    echo "window.GALLERY_DAYS = ["
} > "${MANIFEST}"

grand_total=0
for day_path in "${day_dirs[@]}"; do
    dir="$(basename "${day_path}")"          # e.g. dia_24
    day_num="${dir#dia_}"                     # e.g. 24
    title="${day_num} de julio"

    # Collect this day's photos only.
    shopt -s nullglob nocaseglob
    photos=("${day_path}"*.jpg "${day_path}"*.jpeg)
    shopt -u nocaseglob nullglob

    # Deterministic order: timestamp/name-prefixed filenames sort chronologically.
    IFS=$'\n' photos=($(sort <<<"${photos[*]}")); unset IFS

    total=${#photos[@]}
    grand_total=$((grand_total + total))
    echo "Day ${day_num}: found ${total} photos in ${day_path}"

    {
        echo "  {"
        echo "    title: '${title}',"
        echo "    dir: '${dir}',"
        echo "    photos: ["
    } >> "${MANIFEST}"

    count=0
    for path in "${photos[@]}"; do
        name="$(basename "${path}")"
        count=$((count + 1))

        if [[ ! -f "${THUMBS}/${name}" ]]; then
            sips -Z "${THUMB_MAX}" -s format jpeg -s formatOptions "${THUMB_QUALITY}" \
                "${path}" --out "${THUMBS}/${name}" >/dev/null 2>&1
        fi
        if [[ ! -f "${WEB}/${name}" ]]; then
            sips -Z "${WEB_MAX}" -s format jpeg -s formatOptions "${WEB_QUALITY}" \
                "${path}" --out "${WEB}/${name}" >/dev/null 2>&1
        fi

        echo "      '${name}'," >> "${MANIFEST}"
        printf '\r  processed %d/%d' "${count}" "${total}"
    done
    echo ""

    {
        echo "    ],"
        echo "  },"
    } >> "${MANIFEST}"
done

echo "];" >> "${MANIFEST}"

echo "Wrote manifest with ${grand_total} entries across ${#day_dirs[@]} day(s) -> ${MANIFEST}"
