name: Python microservices checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"] # Usamos la versión 3.13 que es la que usas en el proyecto
        # Lista de los directorios de microservicios para que el workflow los recorra
        service-directory:
          - "services/auth"
          - "services/files"
          - "services/forms"
          - "services/localization"
          - "services/planning"
          - "services/ml_functions"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies for ${{ matrix.service-directory }}
      working-directory: ${{ matrix.service-directory }}
      run: |
        python -m pip install --upgrade pip
        pip install pylint pytest # Instalamos las herramientas de calidad
        pip install -r requirements.txt # Instalamos las dependencias específicas del servicio

    - name: Run Pylint on ${{ matrix.service-directory }}
      working-directory: ${{ matrix.service-directory }}
      run: |
        pylint --fail-under=8.0 . # Ejecutamos Pylint. Falla si el score es menor a 8.0

    - name: Test with Pytest for ${{ matrix.service-directory }}
      working-directory: ${{ matrix.service-directory }}
      run: |
        pytest
